BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Controllers/KienThucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;

namespace WebQLCuaHangThucPham.Controllers
{
    public class KienThucController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        // GET: TinTuc
        public ActionResult Kienthuc()
        {
            return View(db.TinTucs.ToList());
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebQLCuaHangThucPham.Models;

namespace WebQLCuaHangThucPham.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(KhachHang kh)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (kh.Time_Create == null) kh.Time_Create = DateTime.Now;
                    if (kh.Time_Update == null) kh.Time_Update = DateTime.Now;
                    kh.isDelete = 0;
                    kh.isActive = 0;
                    db.KhachHangs.Add(kh);
                    db.SaveChanges();
                    return Json("200");
                }
                else
                {
                    return Json("404");
                }
            }
            catch
            {
                return Json("404");
            }
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult DN(string taikhoan, string matkhau)
        {
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == taikhoan && n.MatKhau == matkhau);
            if (kh != null)
            {
                Session["TaiKhoan"] = kh;
                //Lưu thông tin đăng nhập
                FormsAuthentication.SetAuthCookie(kh.MaKH.ToString() + "|" + kh.HoTen + "|" + kh.DiaChi + "|" + kh.SDT + "|" + kh.Email, true); //id:1,ten:hieu => format: 1|hieu
                //Xử lí phân quyền
                if(kh.Admin == 1)
                {
                    //admin
                    return Json("201");
                }
                else
                {
                    //khachhang
                    return Json("202");
                }
                
            }
            else
            {
                return Json("404");
            }
        }

        public ActionResult DangXuat()
        {
            //Xoa coockie di
            FormsAuthentication.SignOut();
            return Redirect("/trangchu");
        }

    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;
using PagedList;

namespace WebQLCuaHangThucPham.Controllers
{
    public class ProductsController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        //get : laoij sản phẩm trên thanh menu
        public ActionResult SanPham(int? page)
        {
            int pageSize = 12;
            int pagenumber = (page ?? 1);
            List<SanPham> lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).ToList();
            ViewBag.MaLoaiHienTai = 0;
            return View(lstSP.ToPagedList(pagenumber, pageSize));
        }
        public PartialViewResult LoaiSanPham()
        {
            return PartialView(db.LoaiSPs.ToList());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="page"></param>
        /// <param name="MaLoai"></param>
        /// <param name="value">Là các mốc giá: Tất cả,..</param>
        /// <returns></returns>
        public ActionResult ChiTietLoaiSP(int? page, int MaLoai = 0, int value = 0, int valueSelect = 1, string key = "")
        {
            int pageSize = 12;
            int pagenumber = (page ?? 1);
            ViewBag.MaLoaiHienTai = MaLoai;
            ViewBag.ValueSelect = valueSelect;
            List<SanPham> lstSP = new List<SanPham>();
            List<int> minPrice = new List<int>() { 0, 0, 100000, 500000 };
            List<int> maxPrice = new List<int>() { int.MaxValue, 100000, 500000, int.MaxValue };

            //Xử lí key
            key = key.ToLower();
            //Trường hợp lấy ra tất cả sp
            if (MaLoai == 0)
            {
                lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).Where(x => x.TenSP.ToLower().Contains(key) == true). OrderBy(n => n.TenSP).ToList();
            }
            //Lấy theo mã sp truyền vào
            else
            {
                lstSP = db.SanPhams.Where(n => n.MaLoai == MaLoai).Where(x => x.isActive == 0 && x.isDelete == 0).Where(x => x.TenSP.ToLower().Contains(key) == true).OrderBy(n => n.TenSP).ToList();
            }
            //Add giá cho các sản phẩm
            foreach (var item in lstSP)
            {
                double gias = (double)(from Gia in db.GiaSPs where Gia.MaSP == item.MaSP && Gia.Time_Begin < DateTime.Now select Gia.Gia).Single();
                item.Gia = gias;
            }
            //Lọc lần nữa theo giá
            lstSP = lstSP.Where(sp => sp.Gia >= minPrice[value] && sp.Gia < maxPrice[value]).ToList();
            if (valueSelect == 1)
            {
                lstSP = lstSP.ToList();
            }
            else if (valueSelect == 2)
            {
                lstSP = lstSP.OrderByDescending(n => n.Time_Create).ToList();
            }
            else if (valueSelect == 3)
            {
                lstSP = lstSP.OrderBy(n => n.Gia).ToList();
            }
            else if (valueSelect == 4)
            {
                lstSP = lstSP.OrderByDescending(n => n.Gia).ToList();
            }
            if (lstSP.Count == 0)
            {
                ViewBag.lstSanPham = "Không có sản phẩm nào thuộc loại này";
            }

            ViewBag.MaLoai = MaLoai;
            ViewBag.value = value;
            ViewBag.valueSelect = valueSelect;
            ViewBag.key = key;
            ViewBag.lstSanPham = db.SanPhams.ToList();
            return View(lstSP.ToPagedList(pagenumber, pageSize));
        }
        public ActionResult ChiTietSanPham(int MaSP)
        {

            SanPham sp = db.SanPhams.Single(n => n.MaSP == MaSP);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.Anh = db.AnhSPs.Where(n => n.MaSP == MaSP).Take(4).ToList();
            //ViewBag.Gia = db.GiaSPs.Single(n => n.MaSP == MaSP && n.Time_Begin < DateTime.Now ).Gia;
            ViewBag.Gia = (from gia in db.GiaSPs where gia.MaSP == MaSP && gia.Time_Begin < DateTime.Now select gia.Gia).Single();
            //ViewBag.Anh = (from anh in db.AnhSPs where anh.MaSP == MaSP select anh).ToList();
            return View(sp);
        }
        //sản phẩm tương tự 
        public ActionResult SanPhamTuongTu(int MaLoaiSP)
        {
            List<SanPham> lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0 && x.MaLoai == MaLoaiSP).OrderBy(n => n.TenSP).ToList();
            return PartialView(lstSP);
        }
        public PartialViewResult ListSanPham(string masp)
        {
            var sp = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).ToList();
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return PartialView(sp);
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Shared/_LayoutCuaHang.cshtml
@using WebQLCuaHangThucPham.Models
@{
    string[] listOptionSelectValue = { "", "Thứ tự mặc định", "Mới nhất", "Giá từ thấp đến cao", "Giá từ cao đến thấp" };
    ViewBag.ValueSelect = ViewBag.ValueSelect ?? 1;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Cleverfood</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
          integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Frond/css/base.css" rel="stylesheet" />
    <link href="~/Content/Frond/css/CuaHang.css" rel="stylesheet" />
</head>

<body>
    <!-- header -->
    <header>
        <div class="container d-flex align-items-center justify-content-between h-100">
            <div class="menu_main d-flex align-items-center justify-content-between">
                <div class="logo">
                    <a href="@Url.Action("Index", "TrangChu")">cleverfood</a>
                </div>
                <nav class="menu">
                    <ul class="d-flex align-items-center ">
                        <li><a href="@Url.Action("Index","TrangChu")">Trang chủ</a></li>
                        <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
                        <li class="menu1 active">
                            <a href="@Url.Action("SanPham","Products")">cửa hàng</a>
                            <i class="fa-solid fa-angle-down"></i>
                            <ul class="menu2">
                                @Html.Action("LoaiSanPham", "Products")
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
                        <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
                    </ul>
                </nav>
                <ul class="header__icon d-flex align-items-center ">
                    <li><i class="fa-solid fa-magnifying-glass icon-search"></i></li>
                    @Html.Action("CartGioHang", "GioHang")
                    @*chưa đăng nhập*@
                    @if (CurrentUser.MaKH == 0)
                    {
                        <li> <i class="fa-solid fa-user icon-login"></i></li>
                    }

                    @*//Đã đăng nhập*@
                    @if (CurrentUser.MaKH != 0)
                    {
                        <li style="margin-left:3rem">@CurrentUser.TenKH</li>
                        <li>
                            <a href="~/Login/DangXuat"><i class="fa-solid fa-right-from-bracket username"></i></a>
                        </li>
                    }
                </ul>
            </div>
            <div class="mb-menu d-flex align-items-center justify-content-between w-100">
                <div class="icon-menu">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <div class="logo">
                    <a href="@Url.Action("Index", "TrangChu")">cleverfood</a>
                </div>
                <ul class="header__icon d-flex align-items-center ">
                    <li><i class="fa-solid fa-magnifying-glass icon-search"></i></li>

                    @Html.Action("CartGioHang", "GioHang")
                    @*chưa đăng nhập*@
                    @if (CurrentUser.MaKH == 0)
                    {
                        <li> <i class="fa-solid fa-user icon-login"></i></li>
                    }

                    @*//Đã đăng nhập*@
                    @if (CurrentUser.MaKH != 0)
                    {
                        <li>
                            <a href="~/Login/DangXuat"><i class="fa-solid fa-right-from-bracket username"></i></a>
                        </li>
                    }
                </ul>

            </div>
        </div>
    </header>
    <!-- search login cart -->
    @Html.Action("DangNhap", "Login")

    <!-- main -->
    <section class="main">
        <div class="container">
            <div class="title d-flex justify-content-between">
                <ul class=" d-flex ">
                    <li><a href="TrangChu.html">Trang chủ</a></li>
                    <li>/</li>
                    <li><a href="#">Cửa hàng</a></li>
                </ul>
                <div class="selected">
                    <select name="" id="">
                        <option value="@ViewBag.ValueSelect">@listOptionSelectValue[ViewBag.ValueSelect]</option>
                        @for (int i = 0; i < 5; i++)
                        {
                            if (i != ViewBag.ValueSelect && i > 0)
                            {
                                <option value="@i">@listOptionSelectValue[i]</option>
                            }
                        }

                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-lg-3">
                    <div class="store__left">
                        <p>Danh mục Sản phẩm</p>

                        <ul>
                            @*Danh mục loại SP*@
                            @Html.Action("Loaisanpham", "products")
                        </ul>
                    </div>
                    <div class="store__left">
                        <p>LỌC THEO GIÁ</p>
                        <ul class="price">
                            <li value="0">
                                @*<input type="radio" id="check" name="check" value="0">*@
                                <label for="check">Tất cả</label>
                            </li>
                            <li value="1">
                                @*<input type="radio" id="check1" name="check" value="1">*@
                                <label for="check1">Dưới 100,000 đ</label>
                            </li>
                            <li value="2">
                                @*<input type="radio" id="check2" name="check" value="2">*@
                                <label for="check2">Từ 100,000 - 500,000 đ</label>
                            </li>
                            <li value="3">
                                @*<input type="radio" id="check3" name="check" value="3">*@
                                <label for="check3">Trên 500,000 đ</label>
                            </li>
                        </ul>
                    </div>
                    <div class="store__left left__scroll">
                        <p>SẢN PHẨM</p>
                        <ul>
                            @Html.Action("ListSanPham", "Products")
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 col-lg-9 d-flex flex-column justify-content-between">
                    <div class="row list-product">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- footer -->
    <footer>
        <div class="desc">
            <h2>Đăng ký để nhận cập nhật</h2>
            <p>______________</p>
            <p>Để lại email để không bỏ lỡ bất kì ưu đãi nào</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 footer__item">
                    <div class="footer__logo">
                        <img src="~/Content/Frond/img/logo-new.png" alt="">
                    </div>
                    <p>Nhóm 6 - Thiết kế Web</p>
                    <p>123456789</p>
                    <p>nchieu2909@gmail.com</p>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>menu</h4>
                    <ul>
                        <li><a href="@Url.Action("Index", "TrangChu")">Trang chủ</a></li>
                        <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
                        <li><a href="@Url.Action("SanPham", "Products")">Cửa hàng</a></li>
                        <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
                        <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>SẢN PHẨM</h4>
                    <ul>
                        @Html.Action("LoaiSanPham", "Products")
                    </ul>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>INSTAGRAM</h4>
                    <p>Instagram did not return a 200.</p>
                </div>
            </div>
        </div>
        <div class="info ">
            <p> © Bản quyền thuộc về . Thiết kế website Nhóm 6</p>
        </div>
    </footer>
    <div id="ScrollTop" class="">
        <i class="fa-solid fa-angle-up"></i>
    </div>
    <div class="mb_menu">
        <div class="overlay"></div>
        <ul class="">
            <li class="active"><a href="@Url.Action("Index", "TrangChu")">Trang chủ</a></li>
            <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
            <li class="menu1">
                <a href="javascript:void(0)">cửa hàng<i class="fa-solid fa-angle-down"></i></a>
            </li>
            <li>
                <ul class="mb-menu2">
                    @Html.Action("LoaiSanPham", "Products")
                </ul>
            </li>
            <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
            <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
        </ul>
        <i class="fa-solid fa-xmark close-search"></i>
    </div>

</body>
@*<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
        integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/Content/Frond/js/base.js"></script>

</html>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Shared/_LayoutMain.cshtml
@using WebQLCuaHangThucPham.Models
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CleverFood</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
          integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" /
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/Frond/css/base.css">
</head>

<body>
    <!-- header -->
    <header>
        <div class="container d-flex align-items-center justify-content-between h-100">
            <div class="menu_main d-flex align-items-center justify-content-between">
                <div class="logo">
                    <a href="@Url.Action("Index", "TrangChu")">cleverfood</a>
                </div>
                <nav class="menu">
                    <ul class="d-flex align-items-center ">
                        <li class="active"><a href="@Url.Action("Index", "TrangChu")">Trang chủ</a></li>
                        <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
                        <li class="menu1">
                            <a href="@Url.Action("SanPham","Products")">cửa hàng</a>
                            <i class="fa-solid fa-angle-down"></i>
                            <ul class="menu2">
                                @Html.Action("LoaiSanPham", "Products")
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
                        <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
                    </ul>
                </nav>
                <ul class="header__icon d-flex align-items-center ">
                    <li><i class="fa-solid fa-magnifying-glass icon-search"></i></li>
                    @Html.Action("CartGioHang", "GioHang")
                    @*chưa đăng nhập*@
                    @if (CurrentUser.MaKH == 0)
                    {
                        <li> <i class="fa-solid fa-user icon-login"></i></li>
                    }

                    @*//Đã đăng nhập*@
                    @if (CurrentUser.MaKH != 0)
                    {
                        <li style="margin-left:3rem">@CurrentUser.TenKH</li>
                        <li style="margin-left:.5rem">
                            <a href="~/Login/DangXuat"><i class="fa-solid fa-right-from-bracket"></i></a>
                        </li>
                    }
                </ul>
            </div>
            <div class="mb-menu d-flex align-items-center justify-content-between w-100">
                <div class="icon-menu">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <div class="logo">
                    <a href="@Url.Action("Index", "TrangChu")">cleverfood</a>
                </div>
                <ul class="header__icon d-flex align-items-center ">
                    <li><i class="fa-solid fa-magnifying-glass icon-search"></i></li>
                    @Html.Action("CartGioHang", "GioHang")
                    @*chưa đăng nhập*@
                    @if (CurrentUser.MaKH == 0)
                    {
                        <li> <i class="fa-solid fa-user icon-login"></i></li>
                    }

                    @*//Đã đăng nhập*@
                    @if (CurrentUser.MaKH != 0)
                    {
                        <li>
                            <a href="~/Login/DangXuat"><i class="fa-solid fa-right-from-bracket username"></i></a>
                        </li>
                    }
                </ul>

            </div>
        </div>
    </header>
    <!-- search login cart -->
    @Html.Action("DangNhap", "Login")

    <!-- main -->
    @RenderBody()
    <!-- footer -->
    <footer>
        <div class="desc">
            <h2>Đăng ký để nhận cập nhật</h2>
            <p>______________</p>
            <p>Để lại email để không bỏ lỡ bất kì ưu đãi nào</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 footer__item">
                    <div class="footer__logo">
                        <img src="~/Content/Frond/img/logo-new.png" alt="">
                    </div>
                    <p>Nhóm 6 - Thiết kế Web</p>
                    <p>123456789</p>
                    <p>nchieu2909@gmail.com</p>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>menu</h4>
                    <ul>
                        <li><a href="@Url.Action("Index", "TrangChu")">Trang chủ</a></li>
                        <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
                        <li><a href="@Url.Action("SanPham", "Products")">Cửa hàng</a></li>
                        <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
                        <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>SẢN PHẨM</h4>
                    <ul>
                        @Html.Action("LoaiSanPham", "Products")
                    </ul>
                </div>
                <div class="col-md-3 footer__item">
                    <h4>INSTAGRAM</h4>
                    <p>Instagram did not return a 200.</p>
                </div>
            </div>
        </div>
        <div class="info ">
            <p> © Bản quyền thuộc về . Thiết kế website Nhóm 6</p>
        </div>
    </footer>
    <div id="ScrollTop" class="">
        <i class="fa-solid fa-angle-up"></i>
    </div>
    <div class="mb_menu">
        <div class="overlay"></div>
        <ul class="">
            <li class="active"><a href="@Url.Action("Index", "TrangChu")">Trang chủ</a></li>
            <li><a href="@Url.Action("Index", "GioiThieu")">Giới thiệu</a></li>
            <li class="menu1">
                <a href="javascript:void(0)">cửa hàng<i class="fa-solid fa-angle-down"></i></a>
            </li>
            <li>
                <ul class="mb-menu2">
                    @Html.Action("LoaiSanPham", "Products")
                </ul>
            </li>
            <li><a href="@Url.Action("Kienthuc","KienThuc")">kiến thức</a></li>
            <li><a href="@Url.Action("LienHe","LienHe")">Liên hệ</a></li>
        </ul>
        <i class="fa-solid fa-xmark close-search"></i>
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
        integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/Content/Frond/js/base.js"></script>

</html>