BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTT { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public string ND { get; set; }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;

namespace WebQLCuaHangThucPham.Areas.Admins.Controllers
{
    public class TinTucsController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        // GET: Admins/TinTucs
        public ActionResult Index()
        {
            return View(db.TinTucs.ToList());
        }

        // GET: Admins/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admins/TinTucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]

        public ActionResult Create([Bind(Include = "MaTT,MoTa,Anh,ND")] TinTuc tinTuc , HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    image.SaveAs(Server.MapPath("~/Content/Frond/img/" + image.FileName));
                    tinTuc.Anh = System.IO.Path.GetFileName(image.FileName);
                }
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tinTuc);
        }

        // GET: Admins/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admins/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]

        public ActionResult Edit([Bind(Include = "MaTT,MoTa,Anh,ND")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tinTuc);
        }

        // GET: Admins/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admins/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/TinTucs/Create.cshtml
@model WebQLCuaHangThucPham.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/Content/ckeditor/ckeditor.js"></script>
<div class="content">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            @using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
            <div class="form-horizontal ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*<input type="file" name="fileUpload" id="fileUpload" style="width: 100%;" />*@
                        @Html.TextBox("image", "", new { type = "file", @class = "form-control" }  )
                        @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.ND, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <textarea name="ND" id="ckeditor" class="ckeditor"></textarea>
                        @Html.ValidationMessageFor(model => model.ND, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group w-100">
                    <div class="col-md-12 d-flex justify-content-end">
                        <input type="submit" value="Ghi lại" class="btn btn-success mr-1" />
                        <a href="index" class="btn btn-danger mx-1">Quay lại</a>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/TinTucs/Delete.cshtml
@model WebQLCuaHangThucPham.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ND)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/TinTucs/Details.cshtml
@model WebQLCuaHangThucPham.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ND)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaTT }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/TinTucs/Edit.cshtml
@model WebQLCuaHangThucPham.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/Content/ckeditor/ckeditor.js"></script>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TinTuc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTT)

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="ND" id="ckeditor" class="ckeditor">@Model.ND</textarea>
                @Html.ValidationMessageFor(model => model.ND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/TinTucs/Index.cshtml
@model IEnumerable<WebQLCuaHangThucPham.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content">
    <div class="card">

        <div class="card-header d-flex justify-content-end">
            <div class="d-flex justify-content-end w-75 ">
                <a class="btn btn-primary" href="/admins/Tintucs/create">Thêm mới</a>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body ">
            <table class=" table  table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.MoTa)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Anh)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ND)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MoTa)
                        </td>
                        <td>
                            <img src="~/Content/Frond/img/@item.Anh" width="150px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ND)
                        </td>
                     



                        <td class="text-center tac-vu ">
                            <a href="/admins/tintucs/edit/@item.MaTT">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="/admins/tintucs/details/@item.MaTT">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="/admins/tintucs/Delete/@item.MaTT">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>