BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSPs = new HashSet<AnhSP>();
            this.CTDHs = new HashSet<CTDH>();
            this.GiaSPs = new HashSet<GiaSP>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string GTSP { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<System.DateTime> Time_Create { get; set; }
        public Nullable<System.DateTime> Time_Update { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<byte> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSP> AnhSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaSP> GiaSPs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public double Gia { get; set; }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;

namespace WebQLCuaHangThucPham.Areas.Admins.Controllers
{
    public class SanPhamsController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        // GET: Admins/SanPhams
        public ActionResult Index(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                return View(db.SanPhams.Where(x => x.TenSP.ToLower().Contains(searchString)).ToList());
            }
            //ViewBag.sanpham = db.SanPhams.Where(x => x.isDelete == 0 && x.isActive == 0).ToList();
            return View(db.SanPhams.Where(x => x.isDelete == 0).OrderByDescending(x => x.Time_Update).ToList());
        }

        // GET: Admins/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admins/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoai), "MaLoai", "TenLoai");
            //ViewBag.MaLoai = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoai), "MaLoai", "TenLoai");
            return View();
        }

        // POST: Admins/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,GTSP,MaLoai,SL,Time_Create,Time_Update,NguoiTao,isActive,isDelete")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                if (sanPham.Time_Create == null) sanPham.Time_Create = DateTime.Now;
                if (sanPham.Time_Update == null) sanPham.Time_Update = DateTime.Now;
                sanPham.isDelete = 0;
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoai), "MaLoai", "TenLoai");
            return View(sanPham);
        }

        // GET: Admins/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            // tạo nguồn dữ liệu cho danh mục
            ViewBag.MaLoai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // POST: Admins/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,GTSP,MaLoai,SL,Time_Create,Time_Update,NguoiTao,isActive,isDelete")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                sanPham.Time_Update = DateTime.Now;
                sanPham.isDelete = 0;
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // GET: Admins/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admins/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
         public ActionResult Delete([Bind(Include = "MaSP,TenSP,GTSP,MaLoai,SL,Time_Create,Time_Update,NguoiTao,isActive,isDelete")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                sanPham.Time_Update = DateTime.Now;
                sanPham.isDelete = 1;
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LoaiSPs, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;
using PagedList;

namespace WebQLCuaHangThucPham.Controllers
{
    public class ProductsController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        //get : laoij sản phẩm trên thanh menu
        public ActionResult SanPham(int? page)
        {
            int pageSize = 12;
            int pagenumber = (page ?? 1);
            List<SanPham> lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).ToList();
            ViewBag.MaLoaiHienTai = 0;
            return View(lstSP.ToPagedList(pagenumber, pageSize));
        }
        public PartialViewResult LoaiSanPham()
        {
            return PartialView(db.LoaiSPs.ToList());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="page"></param>
        /// <param name="MaLoai"></param>
        /// <param name="value">Là các mốc giá: Tất cả,..</param>
        /// <returns></returns>
        public ActionResult ChiTietLoaiSP(int? page, int MaLoai = 0, int value = 0, int valueSelect = 1, string key = "")
        {
            int pageSize = 12;
            int pagenumber = (page ?? 1);
            ViewBag.MaLoaiHienTai = MaLoai;
            ViewBag.ValueSelect = valueSelect;
            List<SanPham> lstSP = new List<SanPham>();
            List<int> minPrice = new List<int>() { 0, 0, 100000, 500000 };
            List<int> maxPrice = new List<int>() { int.MaxValue, 100000, 500000, int.MaxValue };

            //Xử lí key
            key = key.ToLower();
            //Trường hợp lấy ra tất cả sp
            if (MaLoai == 0)
            {
                lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).Where(x => x.TenSP.ToLower().Contains(key) == true). OrderBy(n => n.TenSP).ToList();
            }
            //Lấy theo mã sp truyền vào
            else
            {
                lstSP = db.SanPhams.Where(n => n.MaLoai == MaLoai).Where(x => x.isActive == 0 && x.isDelete == 0).Where(x => x.TenSP.ToLower().Contains(key) == true).OrderBy(n => n.TenSP).ToList();
            }
            //Add giá cho các sản phẩm
            foreach (var item in lstSP)
            {
                double gias = (double)(from Gia in db.GiaSPs where Gia.MaSP == item.MaSP && Gia.Time_Begin < DateTime.Now select Gia.Gia).Single();
                item.Gia = gias;
            }
            //Lọc lần nữa theo giá
            lstSP = lstSP.Where(sp => sp.Gia >= minPrice[value] && sp.Gia < maxPrice[value]).ToList();
            if (valueSelect == 1)
            {
                lstSP = lstSP.ToList();
            }
            else if (valueSelect == 2)
            {
                lstSP = lstSP.OrderByDescending(n => n.Time_Create).ToList();
            }
            else if (valueSelect == 3)
            {
                lstSP = lstSP.OrderBy(n => n.Gia).ToList();
            }
            else if (valueSelect == 4)
            {
                lstSP = lstSP.OrderByDescending(n => n.Gia).ToList();
            }
            if (lstSP.Count == 0)
            {
                ViewBag.lstSanPham = "Không có sản phẩm nào thuộc loại này";
            }

            ViewBag.MaLoai = MaLoai;
            ViewBag.value = value;
            ViewBag.valueSelect = valueSelect;
            ViewBag.key = key;
            ViewBag.lstSanPham = db.SanPhams.ToList();
            return View(lstSP.ToPagedList(pagenumber, pageSize));
        }
        public ActionResult ChiTietSanPham(int MaSP)
        {

            SanPham sp = db.SanPhams.Single(n => n.MaSP == MaSP);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.Anh = db.AnhSPs.Where(n => n.MaSP == MaSP).Take(4).ToList();
            //ViewBag.Gia = db.GiaSPs.Single(n => n.MaSP == MaSP && n.Time_Begin < DateTime.Now ).Gia;
            ViewBag.Gia = (from gia in db.GiaSPs where gia.MaSP == MaSP && gia.Time_Begin < DateTime.Now select gia.Gia).Single();
            //ViewBag.Anh = (from anh in db.AnhSPs where anh.MaSP == MaSP select anh).ToList();
            return View(sp);
        }
        //sản phẩm tương tự 
        public ActionResult SanPhamTuongTu(int MaLoaiSP)
        {
            List<SanPham> lstSP = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0 && x.MaLoai == MaLoaiSP).OrderBy(n => n.TenSP).ToList();
            return PartialView(lstSP);
        }
        public PartialViewResult ListSanPham(string masp)
        {
            var sp = db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).ToList();
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return PartialView(sp);
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;

namespace WebQLCuaHangThucPham.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();
        public ActionResult Index()
        {
            return View(db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).OrderByDescending(x => x.Time_Create).Take(8).ToList());
        }
        public PartialViewResult KM()
        {
            return PartialView(db.SanPhams.Where(x => x.isActive == 0 && x.isDelete == 0).ToList());
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/ChiTietLoaiSP.cshtml
@using WebQLCuaHangThucPham.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>
@{
    ViewBag.Title = "ChiTietLoaiSP";
    Layout = "~/Views/Shared/_LayoutCuaHang.cshtml";
}


@{
    foreach (var item in Model)
    {
        var db = new QLCuaHangThucPhamEntities1();
        var anh = db.AnhSPs.Where(x => x.MaSP == item.MaSP).First().URL;
        var Gia = db.GiaSPs.Where(x => x.MaSP == item.MaSP && x.Time_Begin < DateTime.Now).First();
        <div class="col-md-4">
            <div class="product_item">
                <div class="item__img">
                    <a href="@Url.Action("ChiTietSanPham","Products",new {@MaSP = item.MaSP})">
                        <img src="~/Content/Frond/img/@anh" alt="Alternate Text" />
                    </a>
                </div>
                <a href="@Url.Action("ChiTietSanPham","Products",new {@MaSP = item.MaSP})">@item.TenSP</a>
                <span><b class="tien">@String.Format("{0:N0}", Gia.Gia)</b> <b>đ</b></span>
            </div>
        </div>
    }
}
<div class="pagination" maloai="@ViewBag.MaLoaiHienTai">
    <ul class="d-flex align-items-center justify-content-center w-100">
        @Html.PagedListPager(Model, page => Url.Action("ChiTietLoaiSP", new { page = page, MaLoai = ViewBag.MaLoai, value = ViewBag.value, valueSelect = ViewBag.valueSelect }))
    </ul>
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/ChiTietSanPham.cshtml
@model WebQLCuaHangThucPham.Models.SanPham
@{
    ViewBag.Title = "ChiTietSanPham";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    var Anh = ViewBag.Anh as List<WebQLCuaHangThucPham.Models.AnhSP>;
    //var gia = ViewBag.Gia as List<WebQLCuaHangThucPham.Models.GiaSP>;
}
<link rel="stylesheet" href="~/Content/Frond/css/ChiTietSanPham.css">

<section class="main mt-5">
    <div class="container">
        <form class="form-sanpham">
            <input type="text" name="MaSP" value="@Model.MaSP" hidden />
            <input type="text" name="Url" value="@Request.Url.ToString()" hidden />
            <div class="row">
                <div class="col-md-6">
                    <div class="product__slide-img">
                        <div class="row">
                            <div class="main__img">
                                <i class="fa-solid fa-chevron-left left"></i>
                                <img src="~/Content/Frond/img/@Anh[0].URL" alt="">
                                <i class="fa-solid fa-chevron-right right"></i>
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col-3 img__slide">
                                <img src="~/Content/Frond/img/@Anh[0].URL" alt="" index="1"
                                     class="active">
                            </div>
                            @for (int i = 1; i < Anh.Count; i++)
                            {
                                <div class="col-3 img__slide">
                                    <img src="~/Content/Frond/img/@Anh[i].URL" alt="" index="@(i + 1)">
                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div class="col-md-6 ">
                    <div class="product__info">
                        <ul class="d-flex align-items-center">
                            <li><a href="@Url.Action("Index", "TrangChu")"> Trang chủ</a></li>
                            <li>/</li>
                            <li><a href="@Url.Action("SanPham", "Products")"> cửa hàng</a></li>
                        </ul>
                        <h2>@Model.TenSP</h2>
                        <p class="price">@String.Format("{0:N0}", ViewBag.Gia) <b>đ</b></p>
                        <span>
                            @Model.GTSP
                            <b>Lorem Ipsum</b> chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và
                            dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành
                            công nghiệp in ấn
                        </span>
                        <div class="add__product d-flex align-items-center">
                            <div class="quantity d-flex align-items-center">
                                <span class="tru">-</span>
                                <input class="input" type="number" name="SL" value="1" min="1">
                                <span class="cong">+</span>
                            </div>
                            <button type="button" style="cursor:pointer;">thêm vào giỏ </button>
                        </div>
                        <div class="row">
                            <div class="col-md-6 ship">
                                <p>Tính phí ship tự động</p>
                                <div class="row">
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-ghn.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-ghtk.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-ninja-van.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-shipchung.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-vib.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-viettle-post.jpg" alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 ship">
                                <p>Thanh toán</p>
                                <div class="row">
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-acb.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-techcombank.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-vib.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-vcb.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-paypal.jpg" alt="">
                                    </div>
                                    <div class="ship__img col-4">
                                        <img src="~/Content/Frond/img/logo-mastercard.jpg" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <h2>Sản phẩm tương tự</h2>
        <div class="slide">
            <div class="product__promotions ">
                @Html.Action("SanPhamTuongTu", "Products", new { @MaLoaiSP = Model.MaLoai })
            </div>
            <i class="fa-solid fa-chevron-left prev"></i>
            <i class="fa-solid fa-chevron-right next"></i>
        </div>
    </div>
</section>

<script>
   
</script>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/ListSanPham.cshtml
@using WebQLCuaHangThucPham.Models;
@model List<SanPham>

@foreach (var item in Model)
{
    var db = new QLCuaHangThucPhamEntities1();
    var anh = db.AnhSPs.Where(x => x.MaSP == item.MaSP).First().URL;
    var Gia = db.GiaSPs.Where(x => x.MaSP == item.MaSP && x.Time_Begin < DateTime.Now).First();

    <li class="d-flex prod">
        <a href="@Url.Action("ChiTietSanPham","Products",new { @MaSP = @item.MaSP})">

            <div class="image">
                <img src="~/Content/Frond/img/@anh" alt="product-1-470x470-100x100">
            </div>
            <div class="info">
                <p>@item.TenSP</p>
                <span>@String.Format("{0:N0}", Gia.Gia) <b>đ</b></span>
            </div>
        </a>

    </li>
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/LoaiSanPham.cshtml
@using WebQLCuaHangThucPham.Models;
@model List<LoaiSP>

@{ 
    int MaLoaiHientai = ViewBag.MaLoaiHienTai ?? 0;
}
@foreach (var item in Model)
{
    <li class=@(MaLoaiHientai == item.MaLoai ? "active" : "")>
        <a href="@Url.Action("ChiTietLoaiSP","Products",new { @MaLoai = item.MaLoai})" id-masp="@item.MaLoai">@item.TenLoai</a>
    </li>
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/SanPham.cshtml
@using WebQLCuaHangThucPham.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>
@{
    ViewBag.Title = "SanPham";
    Layout = "~/Views/Shared/_LayoutCuaHang.cshtml";
}

@{foreach (var item in Model)
    {
        var db = new QLCuaHangThucPhamEntities1();
        var a = db.AnhSPs.Where(x => x.MaSP == item.MaSP).First().URL;
        var Gia = db.GiaSPs.Where(x => x.MaSP == item.MaSP && x.Time_Begin < DateTime.Now).First();

        <div class="col-md-6 col-lg-4 prd">
            <div class="product_item" maloai="@ViewBag.MaLoaiHienTai">
                <div class="item__img">
                    <a href="@Url.Action("ChiTietSanPham", "Products", new { @MaSP = item.MaSP })">
                        <img src="~/Content/Frond/img/@a" alt="Alternate Text" />
                    </a>
                </div>
                <a href="@Url.Action("ChiTietSanPham", "Products", new { @MaSP = item.MaSP })">@item.TenSP</a>
                <span><b class="tien">@String.Format("{0:N0}", Gia.Gia)</b> <b>đ</b></span>
            </div>
        </div>
    }
}

<div class="pagination" maloai="@ViewBag.MaLoaiHienTai"> 
    <ul class="d-flex align-items-center justify-content-center w-100">
       @Html.PagedListPager(Model, page => Url.Action("SanPham", new { page = page, MaLoai = ViewBag.MaLoai }))
    </ul>
</div>

<script>

   
</script>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Views/Products/SanPhamTuongTu.cshtml
@using WebQLCuaHangThucPham.Models;
@model List<SanPham>

@{
    foreach (var item in Model)
    {
        var db = new QLCuaHangThucPhamEntities1();
        var abc = db.AnhSPs.Where(x => x.MaSP == item.MaSP).ToList();
        var Gia = db.GiaSPs.Where(x => x.MaSP == item.MaSP && x.Time_Begin < DateTime.Now).First();
        for (int i = 0; i < abc.Count; i++)
        {
            if (i == 0)
            {
                <div class="col-md-3">
                    <div class="product__promotion__item">
                        <div class="product__promotion__img">
                            <a href="@Url.Action("ChiTietSanPham","Products",new {@MaSP = item.MaSP})">
                                <img src="~/Content/Frond/img/@abc[i].URL" alt="">
                            </a>
                        </div>
                        <a href="@Url.Action("ChiTietSanPham","Products",new {@MaSP = item.MaSP})">@item.TenSP</a>
                        <span> @String.Format("{0:N0}", Gia.Gia)<b>đ</b></span>
                    </div>
                </div>
            }
        }

    }
}