BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Models/AnhSP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhSP
    {
        public int MaAnh { get; set; }
        public int MaSP { get; set; }
        public string TenAnh { get; set; }
        public string URL { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Controllers/AnhSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebQLCuaHangThucPham.Models;
using PagedList;

namespace WebQLCuaHangThucPham.Areas.Admins.Controllers
{
    public class AnhSPsController : Controller
    {
        private QLCuaHangThucPhamEntities1 db = new QLCuaHangThucPhamEntities1();

        // GET: Admins/AnhSPs
        public ActionResult Index(string searchString)
        {

            if (!String.IsNullOrEmpty(searchString))
            {

                searchString = searchString.ToLower();
                return View(db.AnhSPs.Where(x => x.SanPham.TenSP.ToLower().Contains(searchString)).ToList());
            }
            //return View(books.ToList());
            return View(db.AnhSPs.OrderBy(x => x.MaSP).ToList());
        }

       

        // GET: Admins/AnhSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnhSP anhSP = db.AnhSPs.Find(id);
            if (anhSP == null)
            {
                return HttpNotFound();
            }
            return View(anhSP);
        }

        // GET: Admins/AnhSPs/Create
        public ActionResult Create()
        {
            ViewBag.MaSP = new SelectList(db.SanPhams.ToList().Where(x => x.isActive == 0 && x.isDelete == 0).OrderBy(n => n.MaSP), "MaSP", "TenSP");
            return View();
        }

        // POST: Admins/AnhSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "MaAnh,MaSP,TenAnh,URL")] AnhSP anhSP, HttpPostedFileBase image)
        {
           
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    image.SaveAs(Server.MapPath("~/Content/Frond/img/" + image.FileName));
                    anhSP.URL = System.IO.Path.GetFileName(image.FileName);
                }
                db.AnhSPs.Add(anhSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSP = new SelectList(db.SanPhams.ToList().Where(x => x.isActive == 0 && x.isDelete == 0).OrderBy(n => n.MaSP), "MaSP", "TenSP", anhSP.MaSP);
            return View(anhSP);
        }

        // GET: Admins/AnhSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnhSP anhSP = db.AnhSPs.Find(id);
            if (anhSP == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSP = new SelectList(db.SanPhams.ToList().Where(x => x.isActive == 0 && x.isDelete == 0).OrderBy(n => n.MaSP), "MaSP", "TenSP", anhSP.MaSP);
            return View(anhSP);
        }

        // POST: Admins/AnhSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "MaAnh,MaSP,TenAnh,URL")] AnhSP anhSP, HttpPostedFileBase image, FormCollection form)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null)
                    {
                        string _FileName = Path.GetFileName(image.FileName);
                        string _path = Path.Combine(Server.MapPath("~/Content/Frond/img"), _FileName);
                        image.SaveAs(_path);
                        anhSP.URL = _FileName;
                        // get Path of old image for deleting it
                        _path = Path.Combine(Server.MapPath("~/Content/Frond/img"), form["oldimage"]);
                        if (System.IO.File.Exists(_path))
                            System.IO.File.Delete(_path);
                        db.Entry(anhSP).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else { 
                        anhSP.URL = form["oldimage"];
                        db.Entry(anhSP).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                   
                }
                catch (Exception)
                {
                    ViewBag.Message = "không thành công!!";
                }
                return RedirectToAction("Index");
                //AnhSP a = db.AnhSPs.Find(anhSP.MaAnh);
                //if (image != null)
                //{
                //    image.SaveAs(Server.MapPath("~/Content/Frond/img/" + image.FileName));
                //    anhSP.URL = System.IO.Path.GetFileName(image.FileName);
                //}
                //db.Entry(anhSP).State = EntityState.Modified;
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }
            ViewBag.MaSP = new SelectList(db.SanPhams.ToList().Where(x => x.isActive == 0 && x.isDelete == 0).OrderBy(n => n.MaSP), "MaSP", "TenSP", anhSP.MaSP);
            return View(anhSP);
        }

        // GET: Admins/AnhSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnhSP anhSP = db.AnhSPs.Find(id);
            if (anhSP == null)
            {
                return HttpNotFound();
            }
            return View(anhSP);
        }

        // POST: Admins/AnhSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            AnhSP anhSP = db.AnhSPs.Find(id);
            db.AnhSPs.Remove(anhSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/AnhSPs/Create.cshtml
@model WebQLCuaHangThucPham.Models.AnhSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            @using (Html.BeginForm("Create", "Anhsps" ,FormMethod.Post, new {enctype = "multipart/form-data"}))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal ">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group row">
                        @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
           
                            @Html.DropDownList("MaSP", null, htmlAttributes: new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        @Html.LabelFor(model => model.TenAnh, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.TenAnh, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenAnh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @*<input type="file" name="fileUpload" id="fileUpload" style="width: 100%;" />*@
                            @Html.TextBox("image", "", new { type = "file"  })
                            <img id="pictureUpload" width="300" />
                            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group w-100">
                        <div class="col-md-12 d-flex justify-content-end">
                            <input type="submit" value="Ghi lại" class="btn btn-success mr-1" />
                            <a href="index" class="btn btn-danger mx-1">Quay lại</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*@section Upload
{
    <script>
        $(function () {
            //dang ký dự iện click
            $('#fileUpload').trigger('click');
            // bắt sự kiện change dât của file upload
            $('#fileUpload').change(function () {
                // kiểm tra trình duyệt có hỗ trọ from data object không?
                if (window.FormData !== undefined) {
                    // lấy dữ liệu trên fileUpload
                    var fileUpload = $('#fileUpload').get(0);
                    var files = fileUpload.files;
                    // tạo đơi tượng form data
                    var formData = new FormData();
                    // dưa dữ liệu vào form
                    formData.append('files', files[0]);
                    $.ajax({
                        type: 'POST',
                        url: '/admin/Anhsps/create',
                        dataType: "Json",
                        data: {
                           formData
                        },
                        success: function (res) {
                            $('#pictureUpload').ajax('src', res);
                            $('#picture').val(res);
                        }
                    });
                }
            });
        });

    </script>
}*@

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/AnhSPs/Delete.cshtml
@model WebQLCuaHangThucPham.Models.AnhSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal ">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaAnh)

                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.TenAnh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenAnh, new { htmlAttributes = new { @class = "form-control", @readOnly = "readdonly" } })
                        @Html.ValidationMessageFor(model => model.TenAnh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="text" name="name" value="@Model.SanPham.TenSP"  class="form-control" readOnly />
                        @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="~/Content/Frond/img/@Model.URL" width="150px" alt="Alternate Text" />
                        @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                    </div>
                </div>
                

                <div class="form-group d-flex w-100">
                    <div class="col-md-12 d-flex justify-content-end">
                        <input type="submit" value="Xóa" class="btn btn-success mr-1" />
                        <a href="/admins/Anhsps/" class="btn btn-danger mx-1">Quay lại</a>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/AnhSPs/Details.cshtml
@model WebQLCuaHangThucPham.Models.AnhSP

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
            <div class="form-horizontal ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.MaAnh, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.MaAnh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaAnh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.TenAnh, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.TenAnh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenAnh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <input type="file" name="URL" id="URL" value="" />
                        @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control", @readOnly = "readdonly" } })
                        @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group d-flex w-100">
                    <div class="col-md-12 d-flex justify-content-end">
                        <a href="/admins/loaisps/edit/@Model.MaAnh" class="btn btn-success mr-1" title="Sửa danh mục...">Sửa</a>
                        <a href="/admins/loaisps/" class="btn btn-danger mx-1">Quay lại</a>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/AnhSPs/Edit.cshtml
@model WebQLCuaHangThucPham.Models.AnhSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            @using (Html.BeginForm("Edit", "AnhSPs", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.MaAnh)

                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("MaSP", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.TenAnh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenAnh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenAnh, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group d-flex">
                    @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 d-block">
                        <input type="file" name="image" id="image" value="" class="form-control" />
                        <img src="~/Content/Frond/img/@Model.URL" width="200px" />
                        @Html.Hidden("oldimage", @Model.URL)
                        @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group d-flex w-100">
                    <div class="col-md-12 d-flex justify-content-end">
                        <input type="submit" value="Ghi lại" class="btn btn-success mr-1" />
                        <a href="/admins/Anhsps/" class="btn btn-danger mx-1">Quay lại</a>
                    </div>
                </div>
            </div>
            }

        </div>
    </div>
</div>

BTL_Web/WebQLCuaHangThucPham/WebQLCuaHangThucPham/Areas/Admins/Views/AnhSPs/Index.cshtml
@model IEnumerable<WebQLCuaHangThucPham.Models.AnhSP>

@{
    ViewBag.Title = "Ảnh Sản Phẩm";
    Layout = "~/Areas/Admins/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content">
    <div class="card">
       
        <div class="card-header d-flex justify-content-between">
            
            <form class="form-inline" asp-controller ="AnhSPs" asp-action ="Index">
                <input class="form-control mr-sm-2" type="Search" name="searchString" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        

            <div class="d-flex justify-content-end w-75 ">
                <a class="btn btn-primary" href="/admins/anhsps/create">Thêm mới</a>
            </div>
        </div>
            <!-- /.card-header -->
            <div class="card-body ">
                <table class=" table  table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                Mã Ảnh
                            </th>
                            <th>
                                Tên Sản Phẩm
                            </th>
                            <th>
                                Tên Ảnh
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.URL)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.MaAnh
                                </td>
                                <td>
                                    @item.SanPham.TenSP
                                </td>
                                <td>
                                    @item.TenAnh

                                </td>
                                <td>
                                    <img src="~/Content/Frond/img/@item.URL" width="150px" />
                                </td>



                                <td class="text-center tac-vu ">
                                    <a href="/admins/AnhSPs/edit/@item.MaAnh">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="/admins/anhsps/details/@item.MaAnh">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a href="/admins/anhsps/Delete/@item.MaAnh">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
</div>